# name=input("Enter your name: ")
# print(name)



# exp=eval(input("enter a your equation here: "))
# print(exp) #3-2*2



# lenght=float(input("ENtr a length of rectangle"))
# print(lenght)


# age=(input("enter a age"))
# print(age)
# print(type(age))
# x, y = map(int, input("Enter two numbers: ").split())
# print(x + y)

# x, y = input("Enter two values: ").split()
# print(x, y)


# num1=int(input("ENter a number"))
# num2=int(input("ENter a number"))
# result=num1+num2
# dem=("TOtal is "+str(result))
# print(dem)
# print(type(dem))


# name,age=input("ENter a your name").split(",")
# print(name,age)


print(7 / 2)   # Output: 3.5
print(7 // 2)   # Output: 3.5
print(8 / 2)   # Output: 4.0
print(8 // 2)   # Output: 4.0
